// ==UserScript==
// @name         Monitor de Encomendas Simples
// @namespace    http://tampermonkey.net/
// @version      1.2.0
// @description  Lógica estável com painel premium e ajuda ao passar o mouse
// @author       Daniel Alexandre
// @match        https://app.econdos.com.br/*
// @run-at       document-idle
// @grant        none
// ==/UserScript==

(function(){
"use strict";
const STORAGE_HISTORICO="monitor_encomendas_simples_historico";
let apartamentoAtual="",quantidadeRestante=0,sessaoAtiva=false,ultimaURL=location.href,saidaProcessada=false,painelAberto=false;
function normalizarTexto(v){return String(v||"").trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"")}
function escaparHTML(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function obterHistorico(){try{const l=JSON.parse(localStorage.getItem(STORAGE_HISTORICO)||"[]");return Array.isArray(l)?l:[]}catch{return[]}}
function salvarHistorico(apartamento,quantidade,motivo){if(!apartamento||quantidade<=0)return;const agora=new Date(),lista=obterHistorico();lista.unshift({apartamento,quantidade,motivo,dataCompleta:agora.toLocaleString("pt-BR"),timestamp:Date.now()});localStorage.setItem(STORAGE_HISTORICO,JSON.stringify(lista.slice(0,500)));atualizarPainel()}
function encontrarApartamento(){for(const input of document.querySelectorAll("input")){if(input.offsetParent===null)continue;const valor=String(input.value||"").trim();if(/^\d+\/\d+$/.test(valor))return valor}return""}
function lerQuantidadeEncomendas(){for(const el of document.querySelectorAll("small, span, div")){if(el.offsetParent===null)continue;const texto=normalizarTexto(el.textContent),m=texto.match(/(?:^|\s)(\d+)\s+encomenda\(s\)(?:\s|$)/);if(m)return Number(m[1])}return null}
function sincronizarEstado(){const apt=encontrarApartamento(),qtd=lerQuantidadeEncomendas();if(!apt){if(sessaoAtiva&&quantidadeRestante>0)registrarSaida("Campo apagado antes de concluir a baixa");apartamentoAtual="";quantidadeRestante=0;sessaoAtiva=false;saidaProcessada=false;atualizarPainel();return}if(apartamentoAtual&&apt!==apartamentoAtual){if(sessaoAtiva&&quantidadeRestante>0)registrarSaida("Outra residência foi pesquisada antes de concluir a baixa");apartamentoAtual=apt;quantidadeRestante=0;sessaoAtiva=false;saidaProcessada=false}apartamentoAtual=apt;if(qtd===null)return;quantidadeRestante=qtd;if(qtd<=0){sessaoAtiva=false;saidaProcessada=false;atualizarPainel();return}sessaoAtiva=true;saidaProcessada=false;atualizarPainel()}
function registrarSaida(motivo){if(saidaProcessada||!sessaoAtiva||!apartamentoAtual||quantidadeRestante<=0)return;saidaProcessada=true;const texto=quantidadeRestante===1?"1 Encomenda não dado baixa":`${quantidadeRestante} Encomendas não dado baixa`;salvarHistorico(apartamentoAtual,quantidadeRestante,`${texto} · ${motivo}`);sessaoAtiva=false;apartamentoAtual="";quantidadeRestante=0}
setInterval(()=>{if(location.href!==ultimaURL){registrarSaida("Saiu da tela de encomendas");ultimaURL=location.href}sincronizarEstado()},700);
document.addEventListener("click",e=>{const b=e.target.closest("button");if(b&&b.getAttribute("data-testid")==="residence-autocomplete-clear-input-button")registrarSaida("Campo apagado antes de concluir a baixa")},true);
window.addEventListener("pagehide",()=>registrarSaida("Página fechada ou atualizada"),{capture:true});
function adicionarEstilo(){if(document.querySelector("#monitorSimplesCSS"))return;const s=document.createElement("style");s.id="monitorSimplesCSS";s.textContent=`
#botaoMonitorSimples{margin-left:10px;padding:9px 14px;border:1px solid #22c55e;border-radius:8px;background:#080808;color:#22c55e;font:800 11px Arial,sans-serif;cursor:pointer;box-shadow:0 0 14px rgba(34,197,94,.18)}
#botaoMonitorSimples:hover{background:#22c55e;color:#050505}
#painelMonitorSimples,#painelMonitorSimples *{box-sizing:border-box;font-family:Arial,sans-serif}
#painelMonitorSimples{position:fixed;top:70px;right:20px;width:390px;max-height:600px;background:#050505;color:#fff;border:1px solid #22c55e;border-radius:16px;box-shadow:0 0 30px rgba(34,197,94,.28);z-index:2147483647;overflow:hidden}
.cabMonitor{padding:16px;border-bottom:1px solid rgba(34,197,94,.2)}.tituloMonitor{color:#22c55e;font-size:16px;font-weight:900;letter-spacing:.7px}.subMonitor{margin-top:4px;color:#666;font-size:9px;letter-spacing:1.5px}
.statusMonitor{margin:12px;padding:12px;border:1px solid rgba(34,197,94,.22);border-radius:10px;background:#0b0b0b;font-size:11px}.linhaMonitor{display:flex;justify-content:space-between;gap:12px;color:#888;line-height:1.9}.linhaMonitor strong{color:#22c55e;text-align:right}
.acoesMonitor{display:flex;gap:8px;padding:0 12px 12px}.acoesMonitor button{flex:1;padding:8px 10px;border-radius:8px;cursor:pointer;font-size:10px;font-weight:900}#limparHistoricoSimples{border:1px solid #ef4444;background:rgba(239,68,68,.08);color:#ef4444}#fecharMonitorSimples{border:1px solid #22c55e;background:rgba(34,197,94,.08);color:#22c55e}
#listaMonitorSimples{max-height:380px;overflow-y:auto;padding:0 12px 12px}.registroMonitorSimples{border:1px solid rgba(34,197,94,.2);border-radius:10px;padding:11px;margin-bottom:8px;background:#111827;font-size:11px;line-height:1.5}.registroMonitorSimples strong{display:block;color:#22c55e;font-size:16px;margin-bottom:4px}.motivoMonitor{color:#fbbf24}.dataMonitor{margin-top:5px;color:#777;font-size:10px}.vazioMonitor{padding:45px 10px;text-align:center;color:#555;font-size:11px;letter-spacing:1.5px}
@media(max-width:600px){#painelMonitorSimples{top:10px;left:10px;right:10px;width:auto;max-height:calc(100vh - 20px)}}`;document.head.appendChild(s)}
function criarBotao(){adicionarEstilo();if(document.querySelector("#botaoMonitorSimples"))return;const ref=document.querySelector('button[data-testid="delivery-select-multiple-deliveries-button"]');if(!ref)return;const b=document.createElement("button");b.id="botaoMonitorSimples";b.type="button";b.textContent="MONITOR DE ENCOMENDAS";b.title="Como funciona:\n• Digite o apartamento normalmente.\n• O monitor lê a quantidade de encomendas.\n• Se chegar a 0, não registra nada.\n• Se sair deixando 1 ou mais, registra no histórico.";b.addEventListener("click",abrirPainel);ref.insertAdjacentElement("afterend",b)}
function abrirPainel(){if(painelAberto)return;painelAberto=true;const p=document.createElement("div");p.id="painelMonitorSimples";p.innerHTML=`<div class="cabMonitor"><div class="tituloMonitor">MONITOR DE ENCOMENDAS</div><div class="subMonitor">SISTEMA ONLINE</div></div><div class="statusMonitor"><div class="linhaMonitor"><span>APARTAMENTO</span><strong id="aptMonitorSimples">-</strong></div><div class="linhaMonitor"><span>ENCOMENDAS RESTANTES</span><strong id="qtdMonitorSimples">0</strong></div><div class="linhaMonitor"><span>REGISTROS</span><strong id="registrosMonitorSimples">0</strong></div></div><div class="acoesMonitor"><button id="limparHistoricoSimples">LIMPAR HISTÓRICO</button><button id="fecharMonitorSimples">FECHAR</button></div><div id="listaMonitorSimples"></div>`;document.body.appendChild(p);p.querySelector("#limparHistoricoSimples").addEventListener("click",()=>{if(confirm("Deseja limpar todo o histórico?")){localStorage.removeItem(STORAGE_HISTORICO);atualizarPainel()}});p.querySelector("#fecharMonitorSimples").addEventListener("click",()=>{p.remove();painelAberto=false});atualizarPainel()}
function atualizarPainel(){const p=document.querySelector("#painelMonitorSimples");if(!p)return;const h=obterHistorico();p.querySelector("#aptMonitorSimples").textContent=apartamentoAtual||"-";p.querySelector("#qtdMonitorSimples").textContent=String(quantidadeRestante||0);p.querySelector("#registrosMonitorSimples").textContent=String(h.length);const lista=p.querySelector("#listaMonitorSimples");if(!h.length){lista.innerHTML='<div class="vazioMonitor">SEM REGISTROS</div>';return}lista.innerHTML=h.map(i=>`<div class="registroMonitorSimples"><strong>${escaparHTML(i.apartamento)}</strong><div class="motivoMonitor">${escaparHTML(i.motivo)}</div><div class="dataMonitor">${escaparHTML(i.dataCompleta)}</div></div>`).join("")}
const observadorBotao=new MutationObserver(criarBotao);observadorBotao.observe(document.documentElement,{childList:true,subtree:true});criarBotao();sincronizarEstado();
})();