// ==UserScript==
// @name         Painel Plus V1 Modf
// @namespace    http://tampermonkey.net/
// @version      1.3.2
// @description  Monitora apenas Aguardando entrega, salva detalhes da tabela e confirma baixa por X encomenda(s).
// @author       Daniel Alexandre
// @match        https://app.econdos.com.br/*
// @run-at       document-idle
// @grant        none
// ==/UserScript==
(function(){
'use strict';
const SH='painel_plus_historico_v131',SS='painel_plus_sessao_v131',ROTA='/gate/deliveries';
let apt='',x=null,linhas=[],url=location.href,saida=false,logs=[],matrixTimer=null;
const norm=v=>String(v||'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const naTela=()=>location.pathname.includes(ROTA);
function lerHist(){try{const a=JSON.parse(localStorage.getItem(SH)||'[]');return Array.isArray(a)?a:[]}catch{return[]}}
function salvarHist(a){localStorage.setItem(SH,JSON.stringify(a.slice(0,500)));render()}
function log(t,m){logs.unshift({t,m,h:new Date().toLocaleTimeString('pt-BR')});logs=logs.slice(0,100);render()}
function campo(){if(!naTela())return null;const seletores=['input[data-testid="residence-autocomplete-input-search"]','app-residence-autocomplete input','input[placeholder*="unidade" i]'];for(const seletor of seletores){const encontrado=[...document.querySelectorAll(seletor)].find(e=>e.offsetParent!==null);if(encontrado)return encontrado}return null}
function unidade(){if(!naTela())return'';const e=campo(),componente=e?.closest('app-residence-autocomplete');const candidatos=[e?.value,e?.getAttribute('value'),e?.getAttribute('aria-label'),componente?.innerText,componente?.textContent];for(const valor of candidatos){const m=String(valor||'').match(/(?:^|\s)(\d+\/\d+)(?:\s|$)/);if(m)return m[1]}return''}
function filtro(){const b=[...document.querySelectorAll('button[data-testid="delivery-status-filter-button"]')].find(e=>e.offsetParent!==null);return norm(b?.innerText||b?.textContent||b?.title||b?.getAttribute('aria-label')||'')}
function aguardando(){const f=filtro();return f.includes('aguardando')&&f.includes('entrega')}
function contador(){if(!naTela()||!aguardando())return null;for(const e of document.querySelectorAll('small,span')){if(e.offsetParent===null)continue;const m=norm(e.textContent).match(/(?:^|\s)(\d+)\s+encomenda(?:\(s\)|s)?(?:\s|$)/);if(m)return Number(m[1])}return null}
function tabela(){for(const t of document.querySelectorAll('table')){if(t.offsetParent===null)continue;const z=norm(t.innerText);if(z.includes('enviado para')||z.includes('destinatario')||z.includes('status'))return t}return null}
function detalhes(u){const t=tabela(),r=[];if(!t||!u)return r;for(const tr of t.querySelectorAll('tbody tr')){if(tr.offsetParent===null)continue;const c=[...tr.querySelectorAll('td')].map(td=>td.innerText.trim()),un=c.find(v=>/^\d+\/\d+$/.test(v))||'';if(un!==u)continue;r.push({numero:c[0]||'',unidade:un,destinatario:c[2]||'',status:c[3]||'',data:c[4]||'',resumo:c.join(' | ')})}return r}
const chave=i=>[i.numero,i.unidade,i.destinatario,i.status,i.data,i.resumo].join('|');
function upsert(u,q,d,m){if(!u||q<=0)return;const a=lerHist(),i=a.findIndex(v=>v.unidade===u),ant=i>=0?a[i]:null,n={unidade:u,quantidade:q,detalhes:d.length?d:(ant?.detalhes||[]),motivo:m,atualizadoEm:new Date().toLocaleString('pt-BR'),timestamp:Date.now()};i>=0?a[i]=n:a.unshift(n);salvarHist(a)}
function remover(u){const a=lerHist(),n=a.filter(v=>v.unidade!==u);if(n.length!==a.length)salvarHist(n)}
function reconciliar(u,q,d){const a=lerHist(),i=a.findIndex(v=>v.unidade===u);if(i<0)return;if(q===0){remover(u);return}const old=a[i];if(!d.length||!(old.detalhes||[]).length){upsert(u,q,d,'Quantidade atualizada pelo X de Aguardando entrega.');return}const set=new Set(d.map(chave)),rest=old.detalhes.filter(v=>set.has(chave(v)));if(!rest.length){remover(u);return}upsert(u,Math.min(q,rest.length),rest,'Pendência antiga conferida na tabela.')}
function salvarSessao(){localStorage.setItem(SS,JSON.stringify({apt,x,linhas,aguardando:aguardando(),ts:Date.now()}))}
function registrarSaida(m){if(saida||!apt||x===null)return;saida=true;if(x===0){remover(apt);log('BAIXA',`${apt}: X chegou a 0`);return}upsert(apt,x,linhas,m);log('PENDÊNCIA',`${apt}: ${x} restante(s)`)}
function reset(){apt='';x=null;linhas=[];saida=false;localStorage.removeItem(SS);render()}
function sync(){if(!naTela())return;const u=unidade();if(!u){if(apt)registrarSaida('Campo apagado ou unidade abandonada.');reset();return}if(apt&&apt!==u){registrarSaida('Outra unidade foi pesquisada.');apt=u;x=null;linhas=[];saida=false}else apt=u;if(!aguardando()){salvarSessao();render();return}const nx=contador();if(nx===null){render();return}const nd=detalhes(apt),ant=x;x=nx;if(nd.length||nx===0)linhas=nd;saida=false;salvarSessao();if(ant!==nx)log('CONTADOR',`${apt}: ${ant??'-'} → ${nx}`);if(lerHist().some(v=>v.unidade===apt))reconciliar(apt,nx,linhas);if(nx===0)remover(apt);render()}
setInterval(()=>{if(location.href!==url){if(url.includes(ROTA))registrarSaida('Saiu da tela de encomendas.');url=location.href;if(!naTela())reset()}sync();botao()},500);
document.addEventListener('click',e=>{const b=e.target.closest('button');if(b?.getAttribute('data-testid')==='residence-autocomplete-clear-input-button')registrarSaida('Campo apagado antes da baixa.')},true);
window.addEventListener('pagehide',()=>registrarSaida('Página fechada ou atualizada.'),{capture:true});
window.addEventListener('beforeunload',()=>registrarSaida('Aplicativo ou navegador encerrado.'),{capture:true});
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')registrarSaida('Aba ou aplicativo ficou oculto.')});
function css(){if(document.querySelector('#pp505css'))return;const s=document.createElement('style');s.id='pp505css';s.textContent=`
#ppBtn{display:inline-flex!important;align-items:center;gap:8px;margin-left:10px!important}.ppLed{width:8px;height:8px;border-radius:50%;background:#22c55e;box-shadow:0 0 12px #22c55e;animation:ppBlink 1s infinite}@keyframes ppBlink{50%{opacity:.3}}
#ppTip{display:none;position:fixed;width:320px;padding:15px;background:#050505;border:1px solid #22c55e;border-radius:12px;z-index:2147483647;box-shadow:0 0 30px rgba(34,197,94,.35);color:#aaa;font:12px/18px Arial}.ppTT{color:#22c55e;font-weight:bold;font-size:14px;margin-bottom:10px}.ppTA{margin-top:10px;text-align:right;color:#22c55e;font-size:11px}
#ppPanel,#ppPanel *{box-sizing:border-box;font-family:Arial}#ppPanel{position:fixed;top:60px;right:25px;width:410px;height:610px;background:#050505;color:#fff;z-index:2147483646;border-radius:18px;overflow:hidden;border:1px solid #22c55e;box-shadow:0 0 35px rgba(34,197,94,.35)}#ppCanvas{position:absolute;inset:0;width:100%;height:100%;opacity:.12;pointer-events:none}.ppBody{position:relative;z-index:2;padding:18px;height:100%;display:flex;flex-direction:column}.ppTop{display:flex;justify-content:space-between}.ppTitle{font-size:18px;font-weight:bold;color:#22c55e;text-shadow:0 0 15px #22c55e}.ppSub{font-size:10px;color:#777;margin-top:5px;letter-spacing:2px}.ppStatus{margin-top:15px;padding:12px;border-radius:12px;background:#000b;border:1px solid #22c55e44;font-size:12px;line-height:20px}.ppRow{display:flex;justify-content:space-between;gap:10px}.ppVal{color:#22c55e;font-weight:bold;text-align:right}.ppTabs,.ppAct{display:flex;gap:8px;margin-top:10px}.ppTabs button,.ppAct button{flex:1;padding:8px;border-radius:9px;font-size:10px;font-weight:bold;cursor:pointer;background:#111827;color:#888;border:1px solid #22c55e44}.ppTabs .on{color:#22c55e;border-color:#22c55e}.ppArea{flex:1;min-height:0;margin-top:12px;overflow:auto}.ppItem{background:#111827e8;border:1px solid #22c55e33;padding:12px;border-radius:12px;margin-bottom:9px}.ppApt{font-size:18px;font-weight:bold;color:#22c55e}.ppMeta{font-size:10px;color:#fbbf24;margin-top:5px}.ppEmpty{text-align:center;margin-top:80px;color:#555;letter-spacing:2px}.ppFoot{text-align:center;font-size:9px;color:#777;padding-top:8px}
`;document.head.appendChild(s)}
function tooltip(b){document.querySelector('#ppTip')?.remove();const t=document.createElement('div');t.id='ppTip';t.innerHTML=`<div class="ppTT">MONITOR DE ENCOMENDAS</div>O monitor acompanha somente o campo específico da tela de Encomendas.<br><br>O número oficial vem de <b style="color:#22c55e">X encomenda(s)</b> apenas no filtro <b style="color:#22c55e">Aguardando entrega</b>.<br><br>Todos e Entregues podem ser usados normalmente; seus números são ignorados.<br><br>A tabela guarda data, horário, destinatário e status para o botão Detalhes.<br><br>Quando X chega a 0, a baixa é concluída imediatamente.<div class="ppTA">Criado por Daniel Alexandre</div>`;document.body.appendChild(t);b.onmouseenter=()=>{const r=b.getBoundingClientRect();t.style.display='block';t.style.top=`${Math.min(innerHeight-t.offsetHeight-10,r.bottom+8)}px`;t.style.left=`${Math.max(10,Math.min(innerWidth-330,r.left))}px`};b.onmouseleave=()=>t.style.display='none'}
function botao(){css();if(!naTela()){document.querySelector('#ppBtn')?.remove();document.querySelector('#ppTip')?.remove();return}if(document.querySelector('#ppBtn'))return;const ref=document.querySelector('button[data-testid="delivery-select-multiple-deliveries-button"]');if(!ref)return;const b=document.createElement('button');b.id='ppBtn';b.type='button';b.className=ref.className;b.innerHTML='MONITOR DE ENCOMENDAS <span class="ppLed"></span>';b.onclick=abrir;ref.insertAdjacentElement('afterend',b);tooltip(b)}
function abrir(){const old=document.querySelector('#ppPanel');if(old){old.remove();clearInterval(matrixTimer);return}const p=document.createElement('div');p.id='ppPanel';p.innerHTML=`<canvas id="ppCanvas"></canvas><div class="ppBody"><div class="ppTop"><div><div class="ppTitle">MONITOR DE ENCOMENDAS</div><div class="ppSub">SYSTEM ONLINE · V1.3.2</div></div><span class="ppLed"></span></div><div class="ppStatus"><div class="ppRow"><span>UNIDADE</span><span class="ppVal" id="pA">NENHUMA</span></div><div class="ppRow"><span>FILTRO</span><span class="ppVal" id="pF">-</span></div><div class="ppRow"><span>X ENCOMENDA(S)</span><span class="ppVal" id="pX">-</span></div><div class="ppRow"><span>REGISTROS</span><span class="ppVal" id="pR">0</span></div><div class="ppRow"><span>ÚLTIMA AÇÃO</span><span class="ppVal" id="pL">-</span></div></div><div class="ppTabs"><button id="pTH" class="on">HISTÓRICO</button><button id="pTC">TEMPO REAL</button></div><div class="ppAct"><button id="pClear">LIMPAR HISTÓRICO</button><button id="pLogs">LIMPAR CONSOLE</button><button id="pClose">FECHAR</button></div><div class="ppArea" id="pArea"></div><div class="ppFoot">Criado por Daniel Alexandre</div></div>`;document.body.appendChild(p);p.querySelector('#pTH').onclick=()=>{p.dataset.tab='h';p.querySelector('#pTH').classList.add('on');p.querySelector('#pTC').classList.remove('on');render()};p.querySelector('#pTC').onclick=()=>{p.dataset.tab='c';p.querySelector('#pTC').classList.add('on');p.querySelector('#pTH').classList.remove('on');render()};p.querySelector('#pClear').onclick=()=>{if(confirm('Limpar histórico?')){localStorage.removeItem(SH);render()}};p.querySelector('#pLogs').onclick=()=>{logs=[];render()};p.querySelector('#pClose').onclick=()=>{p.remove();clearInterval(matrixTimer)};p.dataset.tab='h';render();matrix()}
function render(){const p=document.querySelector('#ppPanel');if(!p)return;const h=lerHist();p.querySelector('#pA').textContent=apt||'NENHUMA';p.querySelector('#pF').textContent=aguardando()?'AGUARDANDO ENTREGA':'IGNORANDO OUTRO FILTRO';p.querySelector('#pX').textContent=x===null?'-':x;p.querySelector('#pR').textContent=h.length;p.querySelector('#pL').textContent=logs[0]?`${logs[0].t}: ${logs[0].m}`:'SISTEMA INICIADO';const a=p.querySelector('#pArea');if(p.dataset.tab==='c'){a.innerHTML=logs.length?logs.map(l=>`<div class="ppItem"><div class="ppApt">${esc(l.t)}</div><div class="ppMeta">${esc(l.h)} · ${esc(l.m)}</div></div>`).join(''):'<div class="ppEmpty">SEM EVENTOS</div>';return}a.innerHTML=h.length?h.map((v,i)=>`<div class="ppItem"><div class="ppApt">${esc(v.unidade)}</div><div class="ppMeta">${v.quantidade} encomenda(s) sem baixa · ${esc(v.atualizadoEm)}</div><button data-det="${i}">VER DETALHES</button><div id="d${i}" style="display:none;font-size:10px;margin-top:8px">${(v.detalhes||[]).length?v.detalhes.map((d,j)=>`<div><b>Encomenda ${j+1}</b><br>Número: ${esc(d.numero||'-')}<br>Destinatário: ${esc(d.destinatario||'-')}<br>Status: ${esc(d.status||'-')}<br>Data: ${esc(d.data||'-')}</div>${j<v.detalhes.length-1?'<hr>':''}`).join(''):'Detalhes ainda não carregados.'}</div></div>`).join(''):'<div class="ppEmpty">SEM REGISTROS</div>';a.querySelectorAll('[data-det]').forEach(b=>b.onclick=()=>{const d=a.querySelector(`#d${b.dataset.det}`),o=d.style.display!=='block';d.style.display=o?'block':'none';b.textContent=o?'OCULTAR DETALHES':'VER DETALHES'})}
function matrix(){const c=document.querySelector('#ppCanvas'),p=document.querySelector('#ppPanel');if(!c||!p)return;c.width=p.offsetWidth;c.height=p.offsetHeight;const z=c.getContext('2d'),chars='01ABCDEFGHIJKLMNOPQRSTUVWXYZ#$%&@',fs=14,d=Array(Math.floor(c.width/fs)).fill(0).map(()=>Math.random()*40);clearInterval(matrixTimer);matrixTimer=setInterval(()=>{if(!document.body.contains(c)){clearInterval(matrixTimer);return}z.fillStyle='rgba(0,0,0,.12)';z.fillRect(0,0,c.width,c.height);z.fillStyle='#22c55e';z.font=`${fs}px monospace`;d.forEach((y,i)=>{z.fillText(chars[Math.floor(Math.random()*chars.length)],i*fs,y*fs);if(y*fs>c.height&&Math.random()>.975)d[i]=0;d[i]++})},90)}
new MutationObserver(botao).observe(document.documentElement,{childList:true,subtree:true});css();botao();sync();
})();